spark.serializer                 org.apache.spark.serializer.KryoSerializer
spark.sql.catalog.spark_catalog  org.apache.spark.sql.hudi.catalog.HoodieCatalog
spark.sql.extensions             org.apache.spark.sql.hudi.HoodieSparkSessionExtension
spark.jars                       /opt/spark/jars/hudi/hudi-spark3.5-bundle_2.12-1.2.0.jar
spark.driver.memory              4g
