-- Managing streaming tables in production: partition TTL and cleaner settings.
-- Add these to a table's WITH clause.
--
-- Partition TTL: Hudi drops partitions that have not received new data for 180
-- days, judged from its commit metadata (not from the date in the partition name).
-- With inline=true, the check runs after each commit.
-- 'hoodie.partition.ttl.inline'                       = 'true',
-- 'hoodie.partition.ttl.management.strategy.type'     = 'KEEP_BY_TIME',
-- 'hoodie.partition.ttl.strategy.days.retain'         = '180'

-- For the merchants table (not partitioned), bound file versions with the cleaner:
-- 'hoodie.clean.policy'           = 'KEEP_LATEST_COMMITS',
-- 'hoodie.clean.commits.retained' = '3'
