hoodie.table.name=hudi_vendor_payouts
hoodie.datasource.write.table.type=MERGE_ON_READ
hoodie.datasource.write.recordkey.field=vendor_id,order_line_id
hoodie.datasource.write.partitionpath.field=payout_date
hoodie.datasource.write.precombine.field=last_updated_ts
hoodie.index.type=BUCKET
hoodie.bucket.index.num.buckets=4
hoodie.compact.inline.max.delta.commits=2
hoodie.deltastreamer.source.class=org.apache.hudi.utilities.sources.HoodieIncrSource
hoodie.streamer.source.hoodieincr.path=/tmp/hudi/raw/payments
hoodie.deltastreamer.schemaprovider.source.schema.file=schemas/raw_schema.avsc
hoodie.deltastreamer.schemaprovider.target.schema.file=schemas/silver_schema.avsc
hoodie.deltastreamer.transformer.class=com.hudiinaction.chapter06.silver.VendorPayoutTransformer
hoodie.streamer.source.hoodieincr.missing.checkpoint.strategy=READ_UPTO_LATEST_COMMIT

